# Generated by Django 3.2.19 on 2026-10-08 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Parked', 'Parked'), ('Exited', 'Exited')], default='Parked', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
